use sql2237743;


CREATE TABLE `CARD` (
	`card_id` INT NOT NULL AUTO_INCREMENT,
	`card_money` INT,
	`expire_on` DATE,
	PRIMARY KEY (`card_id`)
);

CREATE TABLE `CARD_TYPE` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`pass_type` varchar(20) NOT NULL DEFAULT 'Cartela',
	`price` FLOAT(20) NOT NULL,
	`card_id` INT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `CLIENT` (
	`client_id` INT NOT NULL AUTO_INCREMENT,
	`first_name` varchar(30) NOT NULL,
	`last_name` varchar(30) NOT NULL,
	PRIMARY KEY (`client_id`)
);

CREATE TABLE `TRANSPORT` (
	`transport_id` INT NOT NULL AUTO_INCREMENT,
	`line` INT NOT NULL,
	`type` varchar(30) NOT NULL,
	`charge_per_trip` FLOAT NOT NULL DEFAULT '1.3',
	PRIMARY KEY (`transport_id`)
);

CREATE TABLE `VALIDATION` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`card_id` INT NOT NULL,
	`transport_id` INT NOT NULL,
	`date` DATE NOT NULL,
	`time` TIME NOT NULL,
	PRIMARY KEY (`id`)
);

DROP TABLE CARD;

ALTER TABLE `VALIDATION` MODIFY `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `VALIDATION` CHANGE `time&date` `date&time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `VALIDATION` DROP COLUMN `date`;

ALTER TABLE `CARD` ADD COLUMN `client_id` INT NOT NULL;

ALTER TABLE `CARD_TYPE` MODIFY `price` FLOAT(20);

ALTER TABLE `CARD` ADD CONSTRAINT `CARD_fk0` FOREIGN KEY (`client_id`) REFERENCES `CLIENT`(`client_id`);

ALTER TABLE `CARD_TYPE` ADD CONSTRAINT `CARD_TYPE_fk0` FOREIGN KEY (`card_id`) REFERENCES `CARD`(`card_id`);

ALTER TABLE `CLIENT` ADD CONSTRAINT `CLIENT_fk0` FOREIGN KEY (`card_id`) REFERENCES `CARD`(`card_id`);

ALTER TABLE `VALIDATION` ADD CONSTRAINT `VALIDATION_fk0` FOREIGN KEY (`card_id`) REFERENCES `CARD`(`card_id`);

ALTER TABLE `VALIDATION` ADD CONSTRAINT `VALIDATION_fk1` FOREIGN KEY (`transport_id`) REFERENCES `TRANSPORT`(`transport_id`);

commit;
